ALTER TABLE "DuelRoom"
  ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'duel',
  ADD COLUMN IF NOT EXISTS "matchNumber" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "hostReadyRound" INTEGER NOT NULL DEFAULT -1,
  ADD COLUMN IF NOT EXISTS "guestReadyRound" INTEGER NOT NULL DEFAULT -1,
  ADD COLUMN IF NOT EXISTS "hostRematch" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "guestRematch" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "roundHistory" JSONB NOT NULL DEFAULT '[]';
