export const legalCopy = {
  pl: {
    privacyTitle: "Prywatność", termsTitle: "Zasady korzystania", contact: "Kontakt",
    controller: "Administratorem danych i operatorem Showle jest", updated: "Aktualizacja: 11 września 2026 r.",
    privacy: [
      ["Twoje dane", "Przechowujemy identyfikator konta, zapisane filmy, oceny, recenzje, rankingi, wyniki gier, monety, reakcje na rekomendacje i preferencje. Logowanie i dane konta, w tym adres e-mail, obsługuje Clerk. Dane Showle są przechowywane w PostgreSQL na Neon; aplikacja działa na Vercel."],
      ["Po co je przetwarzamy", "Dane konta i aktywność służą świadczeniu wybranych przez Ciebie funkcji, zapisywaniu postępu i personalizacji poleceń (art. 6 ust. 1 lit. b RODO). Diagnostyka oraz ograniczanie nadużyć służą uzasadnionemu interesowi zapewnienia bezpieczeństwa i niezawodności usługi (art. 6 ust. 1 lit. f RODO)."],
      ["Rekomendacje i dostawcy", "Zwykłe propozycje korzystają z katalogu i Twoich preferencji. Gdy wpiszesz opis lub wybierzesz film odniesienia, opis i publiczne dane filmów mogą być przetwarzane przez OpenRouter oraz jego dostawcę modelu, a tekst wyszukiwania przez Google Gemini. Nie przekazujemy tym modelom identyfikatora konta, prywatnych recenzji ani całej historii oglądania. Nie wpisuj do wyszukiwania danych wrażliwych. Dane filmowe i informacje o dostępności pochodzą z TMDB i JustWatch."],
      ["Pamięć przeglądarki i diagnostyka", "Cookies i pamięć przeglądarki utrzymują sesję logowania, język, postęp gry oraz wybrane preferencje. Nie używamy cookies reklamowych. Sentry służy diagnostyce błędów; automatyczne nagrywanie sesji jest wyłączone. Otwarcie materiału u zewnętrznego dostawcy podlega zasadom tej strony."],
      ["Przechowywanie", "Dane konta przechowujemy do ich wyczyszczenia lub usunięcia konta. Techniczne liczniki wykorzystania rekomendacji są sprzątane po 30 dniach. Wygasłe pokoje pojedynków i wygasłe liczniki żądań są sprzątane po dobie. Sprzątanie wykonuje zadanie utrzymaniowe. Kopie zapasowe podlegają retencji ustawionej przez operatora i nie służą do bieżącego korzystania z danych."],
      ["Twoje prawa", "Możesz uzyskać dostęp do danych, poprawić je, żądać usunięcia, ograniczenia przetwarzania lub przeniesienia, a w odpowiednich przypadkach wnieść sprzeciw. W ustawieniach pobierzesz dane Showle i wyczyścisz dane aplikacji; zarządzanie kontem umożliwia usunięcie konta. Usunięcie konta uruchamia usunięcie powiązanych danych Showle. Masz prawo złożyć skargę do Prezesa Urzędu Ochrony Danych Osobowych. W pozostałych sprawach skontaktuj się z administratorem."],
      ["Dostawcy poza EOG", "Dostawcy infrastruktury i modeli mogą przetwarzać dane poza Europejskim Obszarem Gospodarczym. Administrator odpowiada za weryfikację obowiązujących umów powierzenia, miejsc przetwarzania i odpowiednich zabezpieczeń transferów; informacje o przyjętych zabezpieczeniach można uzyskać kontaktując się z administratorem."],
    ],
    terms: [
      ["Usługa", "Showle umożliwia grę w filmowe zagadki, prowadzenie prywatnej kolekcji oraz wyszukiwanie filmów. Obecna wersja nie pobiera płatności i nie oferuje płatnej subskrypcji."],
      ["Konto i dostęp", "Do części funkcji potrzebujesz konta. Chroń swoje dane logowania. Limity techniczne chronią dostępność aplikacji oraz koszty zapytań do dostawców; są komunikowane w aplikacji. Nie obchodź limitów, nie zakłócaj działania usługi i nie próbuj uzyskać dostępu do cudzych danych."],
      ["Treści i rekomendacje", "Zapisuj wyłącznie treści, do których masz prawo. Rekomendacje są propozycjami, a dopasowanie opisowe może być niedokładne. Dostępność w abonamencie jest informacją z ostatniej aktualizacji i może się zmienić. Showle nie udostępnia filmów ani nie sprzedaje abonamentów serwisów streamingowych."],
      ["Problemy i reklamacje", "Problemy z działaniem, zastrzeżenia dotyczące treści oraz reklamacje można zgłaszać na adres kontaktowy operatora. Opisz problem i podaj informacje pozwalające go odtworzyć; nie przesyłaj haseł. Odpowiemy na podany adres e-mail. Te zasady nie ograniczają praw przysługujących Ci na podstawie obowiązujących przepisów."],
      ["Zakończenie korzystania", "Możesz zakończyć korzystanie w dowolnym momencie oraz pobrać dane, wyczyścić dane aplikacji lub usunąć konto w ustawieniach. Informacje o danych i ich przechowywaniu znajdują się w polityce prywatności."],
    ],
  },
  en: {
    privacyTitle: "Privacy", termsTitle: "Terms of use", contact: "Contact",
    controller: "The data controller and Showle operator is", updated: "Updated: 11 September 2026",
    privacy: [
      ["Your information", "We store your account identifier, saved movies, ratings, reviews, rankings, game results, coins, recommendation reactions and preferences. Clerk handles sign-in and account information, including email. Showle data is stored in PostgreSQL on Neon; the application runs on Vercel."],
      ["Purpose", "Account data and activity provide the features you request, save progress and personalize recommendations (GDPR Article 6(1)(b)). Diagnostics and abuse prevention serve the legitimate interest of maintaining a secure, reliable service (Article 6(1)(f))."],
      ["Recommendations and providers", "Default picks use the catalog and your preferences. When you enter a description or select a reference movie, the description and public movie metadata may be processed by OpenRouter and its model provider, and search text by Google Gemini. We do not send those models your account identifier, private reviews or full viewing history. Do not enter sensitive information in search. Movie and availability data comes from TMDB and JustWatch."],
      ["Browser storage and diagnostics", "Cookies and browser storage maintain sign-in, language, game progress and selected preferences. We do not use advertising cookies. Sentry provides error diagnostics; automatic session recording is disabled. Opening content with an external provider is subject to that website's policies."],
      ["Retention", "Account data is kept until cleared or the account is deleted. Technical recommendation usage counters are cleaned up after 30 days. Expired duel rooms and expired request budgets are cleaned up after one day. A maintenance task performs this cleanup. Backups follow the retention configured by the operator and are not used for regular data processing."],
      ["Your rights", "You may request access, correction, erasure, restriction or portability of your data, and object where applicable. Settings let you download Showle data and clear application data; account management allows account deletion. Deleting an account triggers deletion of its related Showle data. You may lodge a complaint with a data protection authority, including Poland's UODO. Contact the controller for other requests."],
      ["Providers outside the EEA", "Infrastructure and model providers may process data outside the European Economic Area. The controller is responsible for verifying processing agreements, locations and appropriate transfer safeguards. Contact the controller for information about the safeguards in use."],
    ],
    terms: [
      ["The service", "Showle offers movie guessing games, a private movie collection and movie discovery. The current version does not collect payments or offer a paid subscription."],
      ["Account and access", "Some features require an account. Keep your sign-in details secure. Technical limits protect availability and provider costs and are communicated in the application. Do not bypass limits, disrupt the service or attempt to access another person's data."],
      ["Content and recommendations", "Only save content you have the right to use. Recommendations are suggestions and description matching may be inaccurate. Subscription availability reflects the last update and can change. Showle does not stream movies or sell streaming subscriptions."],
      ["Issues and complaints", "Report service issues, content concerns and complaints to the operator's contact address. Describe the issue and how to reproduce it; do not send passwords. We will reply to the email address you provide. These terms do not limit rights granted by applicable law."],
      ["Leaving the service", "You can stop using Showle at any time and download your data, clear application data or delete your account in settings. The privacy policy explains how data is stored and retained."],
    ],
  },
} as const;
