CREATE TABLE IF NOT EXISTS "RecommendationSettings" (
  "userId" TEXT NOT NULL PRIMARY KEY,
  "favoriteIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  "providerIds" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  "onboarded" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
